CREATE DATABASE MINI_PROJETO;
USE MINI_PROJETO;

CREATE TABLE VEICULO (
Cod_Veiculo INT PRIMARY KEY,
Ano INT(4),
Placa VARCHAR(10),
Modelo VARCHAR(50),
Marca VARCHAR(50)
);

CREATE TABLE CLIENTE (
Cod_Cliente INT PRIMARY KEY,
telefone VARCHAR(15),
cpf VARCHAR(14),
Nome VARCHAR(100)
);

CREATE TABLE MECANICO (
Cod_Mecanico INT PRIMARY KEY,
Especialidade VARCHAR(50),
Nome VARCHAR(100)
);

CREATE TABLE SERVICO (
Cod_Veiculo INT PRIMARY KEY,
Valor DECIMAL(10,2),
Descricao VARCHAR(100)
);

CREATE TABLE PECA (
Cod_Peca INT PRIMARY KEY,
Estoque INT,
Nome VARCHAR(100),
Valor_unitario DECIMAL(10,2)
);

CREATE TABLE ORDEM_SERVICO (
Status VARCHAR(20),
Observacao VARCHAR(100),
Data_Abertura VARCHAR(9),
Cod_OS INT PRIMARY KEY,
Data_Fechamento VARCHAR(100)
);

CREATE TABLE POSSUI (
Cod_Veiculo INT,
Cod_Cliente INT,
FOREIGN KEY(Cod_Veiculo) REFERENCES VEICULO (Cod_Veiculo),
FOREIGN KEY(Cod_Cliente) REFERENCES CLIENTE (Cod_Cliente)
);

CREATE TABLE RECEBE (
Cod_Veiculo INT,
Cod_OS INT,
FOREIGN KEY(Cod_Veiculo) REFERENCES VEICULO (Cod_Veiculo),
FOREIGN KEY(Cod_OS) REFERENCES ORDEM_SERVICO (Cod_OS)
);

CREATE TABLE TEM (
Cod_Veiculo INT,
Cod_OS INT,
FOREIGN KEY(Cod_Veiculo) REFERENCES SERVICO (Cod_Veiculo),
FOREIGN KEY(Cod_OS) REFERENCES ORDEM_SERVICO (Cod_OS)
);

CREATE TABLE USA (
Cod_Peca INT,
Cod_OS INT,
FOREIGN KEY(Cod_Peca) REFERENCES PECA (Cod_Peca),
FOREIGN KEY(Cod_OS) REFERENCES ORDEM_SERVICO (Cod_OS)
);

CREATE TABLE EXECUTADA (
Cod_Mecanico INT,
Cod_OS INT,
FOREIGN KEY(Cod_Mecanico) REFERENCES MECANICO (Cod_Mecanico)
);

